# Generated by Django 4.2.30 on 2026-05-18 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_owners_accountability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fund_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='funding.fundpool'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_fundraising',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('governance_approved', 'Governance approved'), ('published', 'Published'), ('registration_open', 'Registration open'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='draft', max_length=32),
        ),
        migrations.CreateModel(
            name='EventMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('proof', models.FileField(blank=True, null=True, upload_to='event_milestone_proof/%Y/')),
                ('proof_original_filename', models.CharField(blank=True, max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='events.event')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_milestones_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'due_date', 'id'],
            },
        ),
    ]
