# Generated by Django 4.2.30 on 2026-05-19 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_fund_pool_event_is_fundraising_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='originated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_originated', to=settings.AUTH_USER_MODEL),
        ),
    ]
