# Generated by Django 4.2.30 on 2026-05-19 15:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('needs', '0004_historicalneed'),
        ('projects', '0005_milestone_tranche_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='programs.program'),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('funding_model', models.CharField(choices=[('inherited', 'Inherited from need'), ('pooled', 'Pooled'), ('anchor', 'Anchor')], default='inherited', max_length=16)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('pending_governance', 'Pending governance'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='proposed', max_length=32)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('budget_currency', models.CharField(default='INR', max_length=8)),
                ('requires_governance_approval', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('students_impacted', models.PositiveIntegerField(blank=True, help_text='Estimated residents / learners served (for impact scorecard). Leave blank if unknown.', null=True, verbose_name='Students / residents impacted')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('need', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='needs.need')),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programs.program')),
            ],
            options={
                'verbose_name': 'historical project',
                'verbose_name_plural': 'historical projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMilestone',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('done', 'Done'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('weight_percent', models.PositiveSmallIntegerField(default=0, help_text='0 = equal weight across milestones')),
                ('completion_notes', models.TextField(blank=True)),
                ('next_tranche_budget_percent', models.PositiveSmallIntegerField(default=0, help_text='% of total project budget unlocked for the next phase after this milestone is completed (with proof). Governance must approve before it counts as released. Use 0 if no tranche at this gate.')),
                ('completion_proof', models.TextField(blank=True, help_text='Required before marking complete when a funding tranche % is set. Evidence for governance.', max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xlsx', 'jpg', 'jpeg', 'png'])])),
                ('completion_proof_original_filename', models.CharField(blank=True, max_length=255)),
                ('tranche_governance_status', models.CharField(choices=[('not_applicable', 'N/A (no tranche)'), ('awaiting_governance', 'Awaiting governance release'), ('released', 'Tranche released'), ('rejected', 'Tranche rejected')], default='not_applicable', max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project')),
            ],
            options={
                'verbose_name': 'historical milestone',
                'verbose_name_plural': 'historical milestones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
