# Generated by Django 4.2.30 on 2026-05-19 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakeholders', '0004_userprofile_batch_year_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstakeholderpersona',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstakeholderpersona',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstakeholderpersona',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stakeholder_type',
            field=models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('hod', 'HOD / Dean'), ('donor', 'Donor'), ('project_lead', 'Project Lead'), ('volunteer', 'Volunteer'), ('finance_controller', 'Finance Controller'), ('governance', 'Governance Team'), ('auditor', 'Auditor'), ('student_beneficiary', 'Student Beneficiary'), ('csr_corporate_donor', 'CSR / Corporate Donor'), ('program_manager', 'Program Manager')], default='volunteer', max_length=32),
        ),
        migrations.AlterField(
            model_name='userrolerequest',
            name='requested_persona',
            field=models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('hod', 'HOD / Dean'), ('donor', 'Donor'), ('project_lead', 'Project Lead'), ('volunteer', 'Volunteer'), ('finance_controller', 'Finance Controller'), ('governance', 'Governance Team'), ('auditor', 'Auditor'), ('student_beneficiary', 'Student Beneficiary'), ('csr_corporate_donor', 'CSR / Corporate Donor'), ('program_manager', 'Program Manager')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userstakeholderpersona',
            name='persona_type',
            field=models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('hod', 'HOD / Dean'), ('donor', 'Donor'), ('project_lead', 'Project Lead'), ('volunteer', 'Volunteer'), ('finance_controller', 'Finance Controller'), ('governance', 'Governance Team'), ('auditor', 'Auditor'), ('student_beneficiary', 'Student Beneficiary'), ('csr_corporate_donor', 'CSR / Corporate Donor'), ('program_manager', 'Program Manager')], max_length=32),
        ),
    ]
