# Generated by Django 4.2.30 on 2026-05-19 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakeholders', '0005_userstakeholderpersona_assigned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUserStakeholderPersona',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('persona_type', models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('hod', 'HOD / Dean'), ('donor', 'Donor'), ('project_lead', 'Project Lead'), ('volunteer', 'Volunteer'), ('finance_controller', 'Finance Controller'), ('governance', 'Governance Team'), ('auditor', 'Auditor'), ('student_beneficiary', 'Student Beneficiary'), ('csr_corporate_donor', 'CSR / Corporate Donor'), ('program_manager', 'Program Manager')], max_length=32)),
                ('assigned_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user stakeholder persona',
                'verbose_name_plural': 'historical user stakeholder personas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('stakeholder_type', models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('hod', 'HOD / Dean'), ('donor', 'Donor'), ('project_lead', 'Project Lead'), ('volunteer', 'Volunteer'), ('finance_controller', 'Finance Controller'), ('governance', 'Governance Team'), ('auditor', 'Auditor'), ('student_beneficiary', 'Student Beneficiary'), ('csr_corporate_donor', 'CSR / Corporate Donor'), ('program_manager', 'Program Manager')], default='volunteer', max_length=32)),
                ('jurisdiction', models.CharField(choices=[('india', 'India'), ('us', 'United States'), ('other', 'Other')], default='india', max_length=16)),
                ('email_opt_in', models.BooleanField(default=False)),
                ('batch_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('linkedin_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.TextField(blank=True, max_length=100, null=True)),
                ('needs_persona_assignment', models.BooleanField(default=False, help_text='True when imported or created without confirmed personas — show in governance roster until cleared.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stakeholders.organization')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user profile',
                'verbose_name_plural': 'historical user profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
