# Generated by Django 4.2.30 on 2026-05-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0006_historicaluserstakeholderpersona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='linkedin_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='stakeholder_type',
            field=models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('hod', 'HOD / Dean'), ('donor', 'Donor'), ('project_lead', 'Project Lead'), ('volunteer', 'Volunteer'), ('finance_controller', 'Finance Controller'), ('governance', 'Governance Team'), ('auditor', 'Auditor'), ('csr_corporate_donor', 'CSR / Corporate Donor'), ('program_manager', 'Program Manager')], default='volunteer', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicaluserstakeholderpersona',
            name='persona_type',
            field=models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('hod', 'HOD / Dean'), ('donor', 'Donor'), ('project_lead', 'Project Lead'), ('volunteer', 'Volunteer'), ('finance_controller', 'Finance Controller'), ('governance', 'Governance Team'), ('auditor', 'Auditor'), ('csr_corporate_donor', 'CSR / Corporate Donor'), ('program_manager', 'Program Manager')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stakeholder_type',
            field=models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('hod', 'HOD / Dean'), ('donor', 'Donor'), ('project_lead', 'Project Lead'), ('volunteer', 'Volunteer'), ('finance_controller', 'Finance Controller'), ('governance', 'Governance Team'), ('auditor', 'Auditor'), ('csr_corporate_donor', 'CSR / Corporate Donor'), ('program_manager', 'Program Manager')], default='volunteer', max_length=32),
        ),
        migrations.AlterField(
            model_name='userrolerequest',
            name='requested_persona',
            field=models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('hod', 'HOD / Dean'), ('donor', 'Donor'), ('project_lead', 'Project Lead'), ('volunteer', 'Volunteer'), ('finance_controller', 'Finance Controller'), ('governance', 'Governance Team'), ('auditor', 'Auditor'), ('csr_corporate_donor', 'CSR / Corporate Donor'), ('program_manager', 'Program Manager')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userstakeholderpersona',
            name='persona_type',
            field=models.CharField(choices=[('foundation_admin', 'Foundation Admin'), ('hod', 'HOD / Dean'), ('donor', 'Donor'), ('project_lead', 'Project Lead'), ('volunteer', 'Volunteer'), ('finance_controller', 'Finance Controller'), ('governance', 'Governance Team'), ('auditor', 'Auditor'), ('csr_corporate_donor', 'CSR / Corporate Donor'), ('program_manager', 'Program Manager')], max_length=32),
        ),
    ]
