# Generated by Django 4.2.30 on 2026-05-19 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=512)),
                ('file_size', models.PositiveIntegerField()),
                ('declared_mime', models.CharField(blank=True, max_length=255)),
                ('actual_mime', models.CharField(blank=True, max_length=255)),
                ('scan_result', models.CharField(choices=[('clean', 'Clean'), ('flagged', 'Flagged'), ('skipped', 'Skipped'), ('error', 'Error')], default='clean', max_length=32)),
                ('scan_detail', models.TextField(blank=True)),
                ('upload_type', models.CharField(choices=[('csv', 'CSV'), ('document', 'Document'), ('photo', 'Photo'), ('proof', 'Proof')], max_length=32)),
                ('action_taken', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('quarantined', 'Quarantined')], max_length=32)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
