# Generated by Django 4.2.30 on 2026-05-19 15:16

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stakeholders', '0005_userstakeholderpersona_assigned_at_and_more'),
        ('needs', '0003_owners_accountability'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNeed',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('funding_model', models.CharField(choices=[('pooled', 'Pooled'), ('anchor', 'Anchor')], default='pooled', max_length=16)),
                ('jurisdiction', models.CharField(choices=[('india', 'India'), ('us', 'United States'), ('both', 'Both')], default='india', max_length=16)),
                ('scope', models.CharField(choices=[('department', 'Department'), ('cross_cutting', 'Cross-cutting')], default='department', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('cataloged', 'Cataloged'), ('pending_governance', 'Pending governance'), ('matched', 'Matched'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=32)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('target_currency', models.CharField(default='INR', max_length=8)),
                ('requires_governance_approval', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stakeholders.organization')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical need',
                'verbose_name_plural': 'historical needs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
