# Generated by Django 4.2.30 on 2026-05-19 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding', '0005_contribution_exchange_rate_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_currency', models.CharField(default='INR', max_length=8)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fund_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='funding.fundpool')),
                ('originated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs_originated', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='owned_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('tranche_percent', models.PositiveSmallIntegerField(default=0)),
                ('proof', models.FileField(blank=True, null=True, upload_to='program_milestone_proof/%Y/')),
                ('completed', models.BooleanField(default=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('tranche_governance_status', models.CharField(choices=[('not_applicable', 'N/A (no tranche)'), ('awaiting_governance', 'Awaiting governance release'), ('released', 'Tranche released'), ('rejected', 'Tranche rejected')], default='not_applicable', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_milestones', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='programs.program')),
            ],
            options={
                'ordering': ['sequence', 'due_date'],
            },
        ),
    ]
